import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";




const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size:38px;
        }
        h3{
          font-size:28px;
        }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, huntingcoder blog, hunting coder" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}
      
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <h1 className={styles.title}>
            <span className="mySpan">Hunting Coder</span>
          </h1>

        </div>
        <div className={styles.imagewrap}>
        {/* <Image className={styles.myImg} src="/homeimg.avif" alt="coder" width={237} height={158} /> */}
        <img src="/homeimg.avif" className={styles.myImg} alt="coder" width={237} height={158}/>
        </div>
        <p className={styles.popular}>A blog for hunting coders by a hunting coder</p>
        <div className={styles.blogs}>
          <h2>Latest Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2024?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2024?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2024?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn JavaScript in 2024?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>

      </main>
    </div>
  );
}
